index:
    path: /
    controller: 'App\Controller\FormulaireController::new'

controllers:
    resource: '../src/Controller/'
    type:     annotation

logout:
    path: /logout

home_page:
    path: /register
    controller: 'App\Controller\UserController::registerAction'

formulaire_index:
    path: /liste
    controller: 'App\Controller\FormulaireController::index'

formulaire_aurevoir:
    path: /aurevoir
    controller: 'App\Controller\FormulaireController::aurevoir'
